version: '3.8'
services:
  app:
    image: ashish727/microfinance
    depends_on:
      - sqlserver
    ports:
      - "80:80"
    networks:
      - appnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Fintex@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

networks:
  appnet:
